### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by itsClay** [itsClay/UnWined#3]

**Comment by itsClay** [comment]
complete!

**Comment by itsClay** [comment]
Feel free to check Heroku app now for review @evhumphrey

**Comment by evhumphrey** [comment]
Before marking this complete, please do the following: 

- On your home screen, explain what Unwined is (right now, it only says unwined, you should explain what your app does in a short phrase)
- make the login / signup buttons on your forms a little taller, and font a little bigger, margin above login / signup button a bit bigger
- the guest login should be a button (that way it's easier to click, and it's more UX-friendly)
- style your dashboard (Hello, user and the logout button)

**Comment by evhumphrey** [comment]
A few changes required:

- [x] Have the login and signup buttons on top right have a slightly dark background (that way there's more contrast): `background: rgba(19, 19, 19, 0.36);`
- [x] Space out the lines in logo a bit more, and add color to logo
- [x] Clear errors between forms

**Comment by itsClay** [comment]
have all complete but the error clear form. I currently have it set up to clear errors on any change for input but having trouble with path changes. lifecycle hooks seem unresponsive since its not triggering a state change.

**Comment by itsClay** [comment]
working!

**Comment by evhumphrey** [comment]
Nice! I won't have you change this now, but right now you are clearing form errors on every state change. I will still work, but it's doing additional work that you don't _really_ need. But it's fine for now (worry about it later).
